export const PROVINCES = [
  "TP HCM",
  "TP Hà Nội",
  "Đồng Nai",
  "TP Hải Phòng",
  "Ninh Bình",
  "Thanh Hóa",
  "An Giang",
  "Phú Thọ",
  "Nghệ An",
  "Bắc Ninh",
  "Đồng Tháp",
  "Vĩnh Long",
  "TP Cần Thơ",
  "Lâm Đồng",
  "Hưng Yên",
  "Gia Lai",
  "Tây Ninh",
  "Đắk Lắk",
  "TP Đà Nẵng",
  "Cà Mau",
  "Khánh Hòa",
  "Quảng Ngãi",
  "Tuyên Quang",
  "Thái Nguyên",
  "Lào Cai",
  "Quảng Trị",
  "Hà Tĩnh",
  "Quảng Ninh",
  "Sơn La",
  "TP Huế",
  "Lạng Sơn",
  "Điện Biên",
  "Cao Bằng",
  "Lai Châu"
];